# Generated by Django 6.1 on 2026-08-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='buyer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
