# Generated by Django 6.1 on 2026-09-02 09:01

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name="Vendor")
    Group.objects.get_or_create(name="Buyer")


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_rename_verified_review_is_verified_and_more"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
