# Generated by Django 6.1 on 2026-09-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_review_rating_review_rating_between_1_and_5_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_product_review_per_user',
        ),
    ]
